name: CICD
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install linux-libc-dev:i386

      - name: Build
        run: |
          cd service_test/
          # sudo rm -rf /usr/local/go
          # pkg=$(curl -s https://go.dev/dl/ | grep -E -o "go[0-9.]{3,}linux-amd64.tar.gz" | head -n1)
          # wget -q https://go.dev/dl/$pkg
          # sudo tar -C /usr/local -xzf $pkg
          # export PATH=$PATH:/usr/local/go/bin
          go version
      #     CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -o ../build/service_test main.go
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: services
      #     path: build/
