name: CICD
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Сборка service_test для 32 битных систем
  build_service_test_i386:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Update
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update -y
          sudo apt install -y linux-libc-dev:i386 gcc-multilib

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd service_test/
          go mod vendor
          CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -o ../build/service_test main.go
      - uses: actions/upload-artifact@v2
        with:
          name: services_i386
          path: build/

  # Сборка service_test для 64 битных систем
  build_service_test_x64:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd service_test/
          go mod vendor
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ../build/service_test main.go
      - uses: actions/upload-artifact@v2
        with:
          name: services_x64
          path: build/